#debug: true
spring:
  #  邮箱发送配置
  mail:
    #    host不配置会注入失败
    host: smtp.163.com
    username: liao20001015@163.com
    password: GRZHROMSBYBCZTXQ
    default-encoding: utf-8
    protocol: smtp
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 10000
          writetimeout: 5000
